version: '3.1'
services:
  uns-app1:
    image: nina150200/uns-app:1.0
    ports:
      - "8081:8080"
    depends_on:
      - postgres
  
  uns-app2:
    image: nina150200/uns-app:1.0
    ports:
      - "8082:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=uns-students
    volumes:
       - ./data-uns:/var/lib/postgresql/data
  
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - uns-app1
      - uns-app2
    ports:
      - "8888:80"

  ftn-app:
    image: nina150200/ftn-app:1.0
    ports:
      - "8001:8081"
    volumes:
      - ./ftn_app/slike:/app/uploads/images
    depends_on:
      postgres-ftn:
        condition: service_healthy

  postgres-ftn:
    image: postgres
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ftn-students
    volumes:
       - ./data-ftn:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s
  
  pmf-app:
    image: nina150200/pmf-app:1.0
    ports:
      - "8002:8081"
    volumes:
      - ./pmf_app/slike:/app/uploads/images
    depends_on:
      postgres-pmf:
        condition: service_healthy

  postgres-pmf:
    image: postgres
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pmf-students
    volumes:
       - ./data-pmf:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s
  
  pravni-app:
    image: nina150200/pravni-app:1.0
    ports:
      - "8003:8081"
    volumes:
      - ./pravni_app/slike:/app/uploads/images
    depends_on:
      postgres-pravni:
        condition: service_healthy

  postgres-pravni:
    image: postgres
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pravni-students
    volumes:
       - ./data-pravni:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s