version: '3.1'
services:
  uns-app:
    build: ./uns-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=uns-students

  ftn-app:
    build: ./ftn_app
    ports:
      - "8001:8081"
    depends_on:
      postgres-ftn:
        condition: service_healthy

  postgres-ftn:
    image: postgres
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=ftn-students
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s