name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_PASSWORD }}
          password: ${{ secrets.DOCKER_USER }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./uns-app
          push: true
          tags: nina150200/uns-app:1.1
          
      - name: Build and push
        id: docker_build2
        uses: docker/build-push-action@v2
        with:
          context: ./ftn_app
          push: true
          tags: nina150200/ftn-app:1.1
      
      - name: Build and push
        id: docker_build3
        uses: docker/build-push-action@v2
        with:
          context: ./pmf_app
          push: true
          tags: nina150200/pmf-app:1.1
      
      - name: Build and push
        id: docker_build4
        uses: docker/build-push-action@v2
        with:
          context: ./pravni_app
          push: true
          tags: nina150200/pravni-app:1.1
